# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JXCategoryTitleViewDEMO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


    pod 'JXCategoryView'
  # Pods for JXCategoryTitleViewDEMO

  target 'JXCategoryTitleViewDEMOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JXCategoryTitleViewDEMOUITests' do
    # Pods for testing
  end

end
