# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WKWebView_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'SnapKit', '~> 5.6.0'
  # Pods for WKWebView_Practice

end
